name: CICD

on:
  push:
    branches: [ main ]
  workflow_dispatch:

jobs:
  deploy:
    runs-on: ubuntu-24.04-arm

    steps:
      - uses: actions/checkout@v4

      - uses: actions/setup-go@v5
        with:
          go-version: '1.24.5'

      - name: Install system dependencies
        run: |
          sudo apt-get update
          sudo apt-get install -y libsystemd-dev

      - name: Build
        run: |
          go mod tidy
          CGO_ENABLED=1 go build -o journalctl-gui ./cmd

      - name: Configure SSH
        run: |
          mkdir -p ~/.ssh
          echo "${{ secrets.PI_SSH_KEY }}" > ~/.ssh/pi_id_ed25519
          chmod 600 ~/.ssh/pi_id_ed25519
          
          cat <<EOF > ~/.ssh/config
          Host pi
            HostName localhost
            User ${{ secrets.PI_USER }}
            IdentityFile ~/.ssh/pi_id_ed25519
            UserKnownHostsFile=/dev/null
            StrictHostKeyChecking no
            ProxyCommand cloudflared access ssh --id ${{ secrets.CF_ACCESS_CLIENT_ID }} --secret ${{ secrets.CF_ACCESS_CLIENT_SECRET }} --hostname ${{ secrets.PI_HOST }}
          EOF

      - name: Install cloudflared
        run: |
          curl -L https://github.com/cloudflare/cloudflared/releases/latest/download/cloudflared-linux-arm64 -o cloudflared
          chmod +x cloudflared
          sudo mv cloudflared /usr/local/bin/

      - name: Deploy file to Raspberry Pi
        run: |
          scp journalctl-gui pi:/usr/local/bin/journalctl-gui_temp

      - name: Stop Service
        run: |
          ssh pi "sudo systemctl stop journalctl-gui"

      - name: Replace binary
        run: |
          ssh pi "sudo mv /usr/local/bin/journalctl-gui_temp /usr/local/bin/journalctl-gui && sudo chmod +x /usr/local/bin/journalctl-gui"

      - name: Start Service
        run: |
          ssh pi "sudo systemctl start journalctl-gui"
